### ISSUE TITLE
Search for gm4

### ISSUE THREAD

**Issue by plicease** [Perl5-Alien/Alien-m4#2]
Some systems, like netbsd have `m4` as a BSD m4.  They may also have gm4 which is the GNU version of m4.  Investigate the if we can use this.  In particular autoconf style packages need to be able to find it.

**Comment by krytarowski** [comment]
BSD m4(1) should be compatible with GNU for regular software.

**Comment by plicease** [comment]
Autoconf is rather picky about its m4 implementation, and is the primary use case for Alien::m4.

https://www.gnu.org/software/autoconf/manual/autoconf.html#Why-GNU-M4

**Comment by plicease** [comment]
New in 0.17: now searching for `m4`, `gm4`, `gnum4` and `$ENV{M4}`, which is the same thing that autoconf does.   Seems to work for `Alien::Autotools` (test needed slight modification),  `Alien::libuv` and `Alien::Hunspell` (at least the part that uses m4, the later two do not currently work on my netbsd vm).
